### ISSUE TITLE
error read ECONNRESET

### ISSUE THREAD

**Issue by Manaus** [jnordberg/wintersmith-livereload#9] opened 2018-04-08 16:03 UTC
I'm getting this error when saving files, the preview server then stops. Am I to use some server app, or npm package for serving events?

**Comment by jnordberg** [comment] 2018-04-08 16:10
Steps to reproduce and versions?

**Comment by jnordberg** [comment] 2018-04-08 16:10
It should not require anything not mentioned in the README

**Comment by Manaus** [comment] 2018-04-08 19:02
Latest version installed of wintersmith via `yarn` on Windows 10, then 

- `wintersmith plugin install livereload` (1.0)
- checked the `config` file to see if the new plugin was mentioned
- `wintersmith preview`
- changed a layout.jade file
- error

Tried out on a Mac, works very fine

**Comment by jnordberg** [comment] 2018-04-08 19:40
Odd, I know that historically the fs events watcher has been buggy on windows but then you should have problems even without livereload since it is used by wintersmith internally.

Can you give me the error output when running `wintersmith preview -vv`

**Comment by Manaus** [comment] 2018-04-08 20:39
Here it is the full narrative

```
  starting preview server
  verbose creating environment - work directory: C:\Users\Max\Web\WsmithOne
  using config file: C:\Users\Max\Web\WsmithOne\config.json
  verbose config: {"locals":{"url":"http://localhost:8080","name":"The Wintersmith's blog","owner":"Someone","description":"Ramblings of an immor(t)al demigod"},"plugins":["./plugins/paginator.coffee","wintersmith-livereload"],"require":{"moment":"moment","_":"underscore","typogr":"typogr"},"jade":{"pretty":true},"markdown":{"smartLists":true,"smartypants":t rue},"paginator":{"perPage":3},"contents":"./contents","ignore":[],"templates":"./templates","views":null,"output":"./build","baseUrl":"/","hostname":null,"port":8080,"_fileLimit":40,"_restartOnConfChange":true,"__filename":"C:\\Users\\Max\\Web\\WsmithOne\\config.json","_cliopts":{"verbose":true,"v":true,"quiet":false,"q":false,"version":false,"V":false,"help":false,"h":false,"c":"./config.json","C":null},"verbose":true,"v":true,"quiet":false,"q":false,"version":false,"V":false,"help":false,"h":false,"c":"./config.json","C":null}
  verbose loading module 'moment' available in locals as 'moment'
  silly loading module: moment
  silly resolved: C:\Users\Max\Web\WsmithOne\node_modules\moment\moment.js
  verbose loading module 'underscore' available in locals as '_'
  silly loading module: underscore
  silly resolved: C:\Users\Max\Web\WsmithOne\node_modules\underscore\underscore.js
  verbose loading module 'typogr' available in locals as 'typogr'
  silly loading module: typogr
  silly resolved: C:\Users\Max\Web\WsmithOne\node_modules\typogr\typogr.js
  verbose watching config file C:\Users\Max\Web\WsmithOne\config.json for changes
  verbose starting preview server
  verbose loading default plugin: page
  verbose loading default plugin: jade
  verbose registering template plugin JadeTemplate that handles: **/*.jade
  verbose loading default plugin: markdown
  verbose registering content plugin MarkdownPage that handles: **/*.*(markdown|mkd|md)
  verbose registering content plugin JsonPage that handles: **/*.json
  verbose loading plugin: ./plugins/paginator.coffee
  silly loading module: ./plugins/paginator.coffee
  silly resolved: C:\Users\Max\Web\WsmithOne\plugins\paginator.coffee
  verbose loading plugin: wintersmith-livereload
  silly loading module: wintersmith-livereload
  silly resolved: C:\Users\Max\Web\WsmithOne\node_modules\wintersmith-livereload\lib\index.js
  LiveReload socket running on port 35729
  silly creating content tree from C:\Users\Max\Web\WsmithOne\contents
  server running on: http://localhost:8080/
  silly loading archive.json
  silly loading about.md
  silly creating content tree from C:\Users\Max\Web\WsmithOne\contents\authors
  silly creating content tree from C:\Users\Max\Web\WsmithOne\contents\articles
  silly creating content tree from C:\Users\Max\Web\WsmithOne\contents\css
  silly loading feed.json
  silly loading authors\baker.json
  silly loading authors\the-wintersmith.json
  silly creating content tree from C:\Users\Max\Web\WsmithOne\contents\articles\another-test
  silly creating content tree from C:\Users\Max\Web\WsmithOne\contents\articles\bamboo-cutter
  silly creating content tree from C:\Users\Max\Web\WsmithOne\contents\articles\hello-world
  silly creating content tree from C:\Users\Max\Web\WsmithOne\contents\articles\markdown-syntax
  silly creating content tree from C:\Users\Max\Web\WsmithOne\contents\articles\red-herring
  silly loading css\main.css
  silly loading articles\another-test\index.md
  silly loading articles\bamboo-cutter\index.md
  silly loading articles\bamboo-cutter\taketori_monogatari.jpg
  silly loading articles\hello-world\index.md
  silly loading articles\markdown-syntax\index.md
  silly loading articles\red-herring\banana.png
  silly loading articles\red-herring\index.md
  verbose contentHandler - /index.html
  200 / PaginatorPage 88ms
  verbose contentHandler - /css/main.css
  verbose contentHandler - /livereload.js
  200 /css/main.css StaticFile 90ms
  200 /livereload.js StaticFile 54ms
  verbose contentHandler - /favicon.ico
  404 /favicon.ico 3ms
  verbose contentHandler - /index.html
  200 / PaginatorPage 23ms

  error read ECONNRESET
```

**Comment by jnordberg** [comment] 2018-04-09 10:36
No stacktrace? What's the exit code?

**Comment by Manaus** [comment] 2018-04-09 10:51
Just as is, after the last line there's the prompt, and voilà.

**Comment by Manaus** [comment] 2018-04-10 10:39
This might seem odd, I can't replicate the problem using Firefox, but it hangs with Chrome. 
Same if I have the two broser windows open. Chrome disrupts the request/response behaviour. Using Firefox returns no problem at all.

**Comment by jnordberg** [comment] 2018-06-03 19:15
That would be helpful, I just tried to reproduce on macOS 10.13.4 node v8.9.4 and same chrome version with no success.

**Comment by ddubau** [comment] 2018-11-01 15:42
I am running into this same issue. ECONNRESET with chrome version 69.0.3497.100 but works fine with Safari. Even tried in chrome incognito to double check that my plugins were not causing the issue. Same issue.

**Comment by ddubau** [comment] 2018-11-06 18:29
I created pull request https://github.com/jnordberg/wintersmith-livereload/pull/10 that adds an event handler for the socket errors. It at least prevents the server from crashing and makes liivereload usable on chome. This however does not solve the root issue on why the socket error is happening in the first place.

**Comment by jnordberg** [comment] 2018-12-04 01:56
Thanks @ddubau! Version 1.0.1 is published to npm and includes the fix. I think the cause was just Chrome not always closing the connection cleanly.

**Closed by jnordberg** 2018-12-04 01:56 UTC
